version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "newlym"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16vl3rve6qjcf"
s3_prefix = "newlym"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "CMSApiUrl=\"https://cms-j25hmdlpya-ts.a.run.app\" CheckoutSuccessUrl=\"https://www.newlymphclinic.com.au/checkout-success\" CheckoutCancelUrl=\"https://www.newlymphclinic.com.au/checkout-failed\""
