version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "newlym"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16vl3rve6qjcf"
s3_prefix = "newlym"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["ResizeFunction=641490273710.dkr.ecr.ap-southeast-2.amazonaws.com/newlym49cf979c/resizefunction5d217ffcrepo"]