AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
    DBUsername:
        NoEcho: true
        Type: String
    DBPassword:
        NoEcho: true
        Type: String

Resources:
    # ==== API Gateway ====
    APIGatewayAPI:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            BinaryMediaTypes:
                - "*/*"
    CheckoutFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: checkout/
            Handler: app.lambdaHandler
            Runtime: nodejs16.x
            Policies: AmazonDynamoDBFullAccess
            Architectures:
                - x86_64
            Events:
                GetCheckoutAPI:
                    Type: Api
                    Properties:
                        Path: /checkout/{checkoutId}
                        Method: GET
                        RestApiId: !Ref APIGatewayAPI
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                Sourcemap: true
                EntryPoints:
                    - app.ts
    # ==== Lambda ====
    ResizeFunction:
        Type: AWS::Serverless::Function
        Properties:
            PackageType: Image
            Policies: AmazonS3FullAccess
            Timeout: 10
            Environment:
                Variables:
                    RAW_IMAGE_BUCKET: !Ref RawImageBucket
                    RESIZED_BUCKET: !Ref ResizedImageBucket
            Architectures:
                - x86_64
            Events:
                ResizeImageAPI:
                    Type: Api
                    Properties:
                        Path: /resize/{file}
                        Method: GET
                        RestApiId: !Ref APIGatewayAPI
        Metadata:
            DockerTag: nodejs16.x-v1
            DockerContext: resize/
            Dockerfile: Dockerfile
    # ==== CloudFront ====
    ResizeCloudFront:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Origins:
                    - DomainName: !Sub "${APIGatewayAPI}.execute-api.${AWS::Region}.amazonaws.com"
                      Id: ResizeApi
                      OriginPath: /Prod/resize
                      CustomOriginConfig:
                          HTTPPort: 80
                          HTTPSPort: 443
                          OriginProtocolPolicy: https-only
                          OriginSSLProtocols:
                              - TLSv1.2
                Enabled: true
                DefaultCacheBehavior:
                    TargetOriginId: ResizeApi
                    ViewerProtocolPolicy: allow-all
                    OriginRequestPolicyId: !Ref ResizeCloudFrontOriginPolicy
                    CachePolicyId: !Ref ResizeCloudFrontCachePolicy
    ResizeCloudFrontOriginPolicy:
        Type: AWS::CloudFront::OriginRequestPolicy
        Properties:
            OriginRequestPolicyConfig:
                Name: ResizeCloudFrontOriginPolicy
                HeadersConfig:
                    HeaderBehavior: none
                CookiesConfig:
                    CookieBehavior: none
                QueryStringsConfig:
                    QueryStringBehavior: whitelist
                    QueryStrings:
                        - size
    ResizeCloudFrontCachePolicy:
        Type: AWS::CloudFront::CachePolicy
        Properties:
            CachePolicyConfig:
                Name: ResizeCloudFrontCachePolicy
                MinTTL: 1
                MaxTTL: 31536000
                DefaultTTL: 86400
                ParametersInCacheKeyAndForwardedToOrigin:
                    HeadersConfig:
                        HeaderBehavior: none
                    CookiesConfig:
                        CookieBehavior: none
                    EnableAcceptEncodingBrotli: true
                    EnableAcceptEncodingGzip: true
                    QueryStringsConfig:
                        QueryStringBehavior: whitelist
                        QueryStrings:
                            - size
    # ==== RDS ====
    CMSDatabase:
        Type: "AWS::RDS::DBInstance"
        Properties:
            DBInstanceIdentifier: CMS
            DBName: strapi
            DBInstanceClass: db.t3.micro
            AllocatedStorage: 100
            Engine: postgres
            MasterUsername: !Ref DBUsername
            MasterUserPassword: !Ref DBPassword
            PubliclyAccessible: true
    # ==== S3 ====
    RawImageBucket:
        Type: AWS::S3::Bucket
        Properties:
            OwnershipControls:
                Rules:
                    - ObjectOwnership: BucketOwnerPreferred
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true
    ResizedImageBucket:
        Type: AWS::S3::Bucket
        Properties:
            OwnershipControls:
                Rules:
                    - ObjectOwnership: BucketOwnerPreferred
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true
