AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
    CheckoutFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: checkout/
            Handler: app.lambdaHandler
            Runtime: nodejs16.x
            Policies: AmazonDynamoDBFullAccess
            Architectures:
                - x86_64
            Events:
                GetCheckoutAPI:
                    Type: Api
                    Properties:
                        Path: /checkout/{checkoutId}
                        Method: GET
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                Sourcemap: true
                EntryPoints:
                    - app.ts
    CheckoutConfigTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            TableName: CheckoutConfig
            AttributeDefinitions:
                - AttributeName: checkoutId
                  AttributeType: S
            KeySchema:
                - AttributeName: checkoutId
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST
