AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
    DBUsername:
        Type: String
    DBPassword:
        Type: String
    StripeKey:
        Type: String
    StripeWebhookSecret:
        Type: String
    CMSApiUrl:
        Type: String
    CMSApiToken:
        Type: String
    CheckoutSuccessUrl:
        Type: String
    CheckoutCancelUrl:
        Type: String
    NotionKey:
        Type: String
    NotionOrderDatabaseId:
        Type: String

Resources:
    # ==== API Gateway ====
    APIGatewayAPI:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
    # ==== Lambda ====
    CheckoutFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: checkout/
            Handler: app.lambdaHandler
            Runtime: nodejs16.x
            Environment:
                Variables:
                    STRIPE_KEY: !Ref StripeKey
                    API_URL: !Ref CMSApiUrl
                    API_TOKEN: !Ref CMSApiToken
                    SUCCESS_URL: !Ref CheckoutSuccessUrl
                    CANCEL_URL: !Ref CheckoutCancelUrl
            Architectures:
                - x86_64
            Events:
                GetCheckoutAPI:
                    Type: Api
                    Properties:
                        Path: /checkout/{bundleId}
                        Method: GET
                        RestApiId: !Ref APIGatewayAPI
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                Sourcemap: true
                EntryPoints:
                    - app.ts
    WebhookStripeCheckoutSuccessFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: stripe-webhook/
            Handler: app.lambdaHandler
            Runtime: nodejs16.x
            Policies: AmazonSNSFullAccess
            Environment:
                Variables:
                    STRIPE_KEY: !Ref StripeKey
                    STRIPE_WEBHOOK_SECRET: !Ref StripeWebhookSecret
                    TOPIC_ARN: !Ref WebhookStripeCheckoutSuccessSNS
            Architectures:
                - x86_64
            Events:
                GetCheckoutAPI:
                    Type: Api
                    Properties:
                        Path: /webhooks/stripe/checkout-success
                        Method: POST
                        RestApiId: !Ref APIGatewayAPI
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                Sourcemap: true
                EntryPoints:
                    - app.ts
    OrderNotificationFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: order-notification/
            Handler: app.lambdaHandler
            Runtime: nodejs16.x
            Environment:
                Variables:
                    NOTION_KEY: !Ref NotionKey
                    NOTION_DATABASE_ID: !Ref NotionOrderDatabaseId
            Architectures:
                - x86_64
            Events:
                WebhookStripeCheckoutSuccessSQS:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt WebhookStripeCheckoutSuccessEmailSQS.Arn
                        BatchSize: 1
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                Sourcemap: true
                EntryPoints:
                    - app.ts
    # ==== SNS ====
    WebhookStripeCheckoutSuccessSNS:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: WebhookStripeSNS
            Subscription:
                - Protocol: sqs
                  Endpoint: !GetAtt WebhookStripeCheckoutSuccessEmailSQS.Arn
    # ==== SQS ====
    WebhookStripeCheckoutSuccessEmailSQS:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: WebhookStripeCheckoutSuccessEmailSQS
    WebhookStripeCheckoutSuccessEmailSQSPolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
            Queues:
                - !Ref WebhookStripeCheckoutSuccessEmailSQS
            PolicyDocument:
                Statement:
                    - Sid: allow-sns-webhook-stripe-checkout-success-email
                      Effect: Allow
                      Principal: "*"
                      Resource: !GetAtt WebhookStripeCheckoutSuccessEmailSQS.Arn
                      Action:
                          - SQS:SendMessage
                      Condition:
                          ArnEquals:
                              aws:SourceArn: !Ref WebhookStripeCheckoutSuccessSNS
    # ==== CloudFront ====
    CMSCloudFront:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Origins:
                    - DomainName: !Sub "${CMSImageBucket}.s3.${AWS::Region}.amazonaws.com"
                      Id: CMSS3Bucket
                      S3OriginConfig:
                          OriginAccessIdentity: !Join ["", ["origin-access-identity/cloudfront/", !Ref CMSCloudFrontOAI]]
                Enabled: true
                DefaultCacheBehavior:
                    TargetOriginId: CMSS3Bucket
                    ViewerProtocolPolicy: allow-all
                    ForwardedValues:
                        QueryString: false
    CMSCloudFrontOAI:
        Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
        Properties:
            CloudFrontOriginAccessIdentityConfig:
                Comment: "Restrict S3 access"
    # ==== S3 ====
    CMSImageBucket:
        Type: AWS::S3::Bucket
        Properties:
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true
    CMSImageBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref CMSImageBucket
            PolicyDocument:
                Statement:
                    - Action: s3:GetObject
                      Effect: Allow
                      Resource: !Sub "arn:aws:s3:::${CMSImageBucket}/*"
                      Principal:
                          CanonicalUser: !GetAtt CMSCloudFrontOAI.S3CanonicalUserId
    # ==== RDS ====
    CMSDatabase:
        Type: "AWS::RDS::DBInstance"
        Properties:
            DBInstanceIdentifier: CMS
            DBName: strapi
            DBInstanceClass: db.t3.micro
            AllocatedStorage: 100
            Engine: postgres
            MasterUsername: !Ref DBUsername
            MasterUserPassword: !Ref DBPassword
            PubliclyAccessible: true
