AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
    DBUsername:
        NoEcho: true
        Type: String
    DBPassword:
        NoEcho: true
        Type: String

Resources:
    CheckoutFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: checkout/
            Handler: app.lambdaHandler
            Runtime: nodejs16.x
            Policies: AmazonDynamoDBFullAccess
            Architectures:
                - x86_64
            Events:
                GetCheckoutAPI:
                    Type: Api
                    Properties:
                        Path: /checkout/{checkoutId}
                        Method: GET
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                Sourcemap: true
                EntryPoints:
                    - app.ts
    ResizeFunction:
        Type: AWS::Serverless::Function
        Properties:
            PackageType: Image
            Architectures:
                - x86_64
        Metadata:
            DockerTag: nodejs16.x-v1
            DockerContext: resize/
            Dockerfile: Dockerfile
    CheckoutConfigTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
            TableName: CheckoutConfig
            AttributeDefinitions:
                - AttributeName: checkoutId
                  AttributeType: S
            KeySchema:
                - AttributeName: checkoutId
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST
    CMSDatabase:
        Type: "AWS::RDS::DBInstance"
        Properties:
            DBInstanceIdentifier: CMS
            DBName: strapi
            DBInstanceClass: db.t3.micro
            AllocatedStorage: 100
            Engine: postgres
            MasterUsername: !Ref DBUsername
            MasterUserPassword: !Ref DBPassword
            PubliclyAccessible: true
    RawImageBucket:
        Type: AWS::S3::Bucket
    ResizedImageBucket:
        Type: AWS::S3::Bucket
